# Netlify configuration file

# Build settings
[build]
  # Use the dist directory for deployment
  publish = "dist"
  # No build command needed since files are already built
  command = ""

# Environment variables 
[build.environment]
  VITE_API_URL = "https://7a407b74-b1a3-43f7-bf8a-d00fad3554e3-00-15b02g7uh8r3y.riker.replit.dev/api"

# Handle single page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200