# Netlify configuration file

# Build settings
[build]
  # What folder to publish for deployment - use root folder
  publish = "."
  # No build command needed
  command = ""

# Environment variables 
[build.environment]
  VITE_API_URL = "https://7a407b74-b1a3-43f7-bf8a-d00fad3554e3-00-15b02g7uh8r3y.riker.replit.dev/api"