[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://7a407b74-b1a3-43f7-bf8a-d00fad3554e3-00-15b02g7uh8r3y.riker.replit.dev/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200